// x_source.rs — mawx WI-5: source schemes + registry raw-fetch
// (ψ/design/mawx-spec.md §2.2 resolution/fetch, §2.3 source schemes).
//
// The scheme set is a CLOSED, audited enum — not a plugin system for the
// resolver itself (spec §2.3: resolvers run before trust is established, so
// they must be audited core code; third parties bridge by laying out their
// repo like maw-plugins, never by injecting resolver code).
//
// Deterministic-core / IO-edge split:
// - PURE (unit-testable, no network/filesystem): `route_x_spec`,
//   `resolve_x_registry_verb`, `parse_x_registry`, `lookup_x_registry_verb`,
//   `x_registry_url`, `x_raw_file_url`, `x_manifest_fetch_info`,
//   `check_x_pin_chain`, `x_resolution_plan`.
// - IO EDGE (network via reqwest, filesystem via x_cache): `fetch_x_registry`,
//   `resolve_x_spec`, `execute_x_fetch`.
//
// Fetch discipline (spec §2.2 "the lean path"):
// - Registry bare verb → raw-fetch ONLY plugin.json + the pinned artifact at
//   the entry's commit. NO git clone on the happy path.
// - Every fetched artifact is sha256-verified against the full pin chain
//   (registry entry == manifest pin == explicit `--sha256`) BEFORE the bytes
//   are handed to `x_cache_put` (which re-verifies).
// - gh:/shorthand specs with a branch/tag ref that raw-fetch cannot pin →
//   shallow clone into a temp dir (same hygiene as `install_from_git`), then
//   the shared WI-1 `verify_package_dir` fork.
// - `file:`/local dirs never write to the cache (spec §2.3 local dev route).
// - NO auth headers, ever: public repos only (same posture as the http
//   host-fn precedent, which strips auth).

/// Default registry repo owner (spec §2.2: single default registry in V1).
pub const X_DEFAULT_REGISTRY_OWNER: &str = "Soul-Brews-Studio";

/// Default registry repo name.
pub const X_DEFAULT_REGISTRY_REPO: &str = "maw-plugins";

/// Raw-file host every GitHub fetch goes through.
pub const X_RAW_HOST: &str = "https://raw.githubusercontent.com";

/// Default network timeout for one raw-fetch request.
pub const X_FETCH_TIMEOUT_SECS: u64 = 30;

/// One entry of the registry's flat `verb → entry` map
/// (`registry.json`, generated by maw-plugins CI — spec WI-9).
#[derive(Debug, Clone, PartialEq, Eq, serde::Deserialize)]
pub struct XRegistryEntry {
    /// Commit SHA the package is pinned at (raw fetch at this commit is
    /// immutable end-to-end).
    pub commit: String,
    /// Artifact pin, `sha256:<64 lowercase hex>`.
    pub sha256: String,
    /// Package dir inside the registry repo (e.g. `packages/20-costs`).
    pub path: String,
    /// Package version at pin time.
    pub version: String,
    /// Capability grants (display/trust-card data; the manifest stays the
    /// enforcement source).
    #[serde(default)]
    pub capabilities: Vec<String>,
}

/// Registry-sourced resolution metadata carried into the fetch plan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct XRegistryResolution {
    /// Verb the registry resolved.
    pub verb: String,
    /// Registry entry version.
    pub version: String,
    /// Registry entry capabilities.
    pub capabilities: Vec<String>,
    /// Registry entry pin (`sha256:<hex>`) — first link of the pin chain.
    pub sha256: String,
}

/// The files-to-fetch plan for one resolved source (spec §2.3: every scheme
/// funnels into the same verify gate; trust is scheme-independent).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum XFetchPlan {
    /// Raw-fetch `plugin.json` + the pinned artifact at an immutable commit —
    /// the primary, clone-free path.
    Raw {
        /// GitHub owner.
        owner: String,
        /// GitHub repo.
        repo: String,
        /// Commit SHA the files are fetched at.
        commit: String,
        /// Package dir inside the repo (empty = repo root).
        package_path: String,
        /// Registry metadata when the plan came from a registry verb.
        registry: Option<XRegistryResolution>,
    },
    /// Shallow `git clone` fallback for refs raw-fetch cannot pin
    /// (branch/tag) and for non-GitHub git URLs.
    Clone {
        /// Clone URL.
        url: String,
        /// Branch/tag passed to `git clone --branch`.
        reference: Option<String>,
        /// Package dir inside the clone.
        subpath: Option<String>,
    },
    /// Local dev dir (`file:`/`./`) — verified in place, never cached.
    Local {
        /// The path as given in the spec.
        path: String,
    },
}

/// A fully resolved fetch: canonical source string, the pinned commit when
/// one is known pre-fetch, and the files-to-fetch plan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedFetch {
    /// Canonical source string (trust-store / lock form, spec §2.1).
    pub canonical_source: String,
    /// Pinned commit when the plan is already immutable (raw plans); `None`
    /// until the clone fallback resolves its ref.
    pub commit: Option<String>,
    /// What to fetch and how.
    pub plan: XFetchPlan,
}

/// First routing decision for a parsed spec: either the verb needs the
/// registry (network) to resolve, or the spec resolves purely.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum XRoute {
    /// Bare verb — resolve via `registry.json` (spec §2.2 step 3d).
    Registry {
        /// The verb to look up.
        verb: String,
        /// Optional `@ref` carried by the verb spec.
        reference: Option<XGitRef>,
    },
    /// Everything the spec pins directly, no registry needed.
    Resolved(ResolvedFetch),
}

/// The spec §2.1 `--dry-run` JSON plan:
/// `{source, commit, path, sha256, capabilities, sdk}`. Unknown-before-fetch
/// fields serialize as `null`.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct XResolutionPlan {
    /// Canonical source string.
    pub source: String,
    /// Pinned commit, when known.
    pub commit: Option<String>,
    /// Package dir inside the source repo, when known.
    pub path: Option<String>,
    /// Artifact pin (`sha256:<hex>`), when known.
    pub sha256: Option<String>,
    /// Capability grants, when known.
    pub capabilities: Option<Vec<String>>,
    /// Manifest `sdk` requirement — only known after the manifest is fetched.
    pub sdk: Option<String>,
}

/// IO-edge tuning for the fetch executor.
#[derive(Debug, Clone, Copy)]
pub struct XFetchOptions<'a> {
    /// CAS root (WI-6 `x_cache_root`).
    pub cache_root: &'a std::path::Path,
    /// Per-request network timeout in seconds.
    pub timeout_secs: u64,
    /// Unix seconds threaded into cache writes (no clock reads here).
    pub now: u64,
}

/// Outcome of one executed fetch: the enriched resolution plan, the
/// package-shaped dir the plugin runs from, and whether it lives in the CAS.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct XFetchedPackage {
    /// Resolution plan enriched with post-fetch facts (sha256, sdk, caps).
    pub resolution: XResolutionPlan,
    /// Package dir: the CAS entry dir, or the local dir for `file:` specs.
    pub package_dir: std::path::PathBuf,
    /// `false` only for the local dev route (spec: no cache write).
    pub cached: bool,
}

/// Everything the raw-fetch path needs from a fetched `plugin.json`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct XManifestFetchInfo {
    /// Manifest `name`.
    pub name: String,
    /// Dispatch verb: `cli.command`, falling back to `name` (spec §2.2:
    /// dispatch keys on `cli.command`, not the directory name).
    pub verb: String,
    /// Manifest `version`.
    pub version: String,
    /// `target == "wasm"` — the only raw-fetchable tier in V1.
    pub target_wasm: bool,
    /// Normalized `artifact.path` (leading `./` stripped), when present.
    pub artifact_path: Option<String>,
    /// Normalized `artifact.sha256` pin, when present.
    pub artifact_sha256: Option<String>,
    /// `bundledArtifacts[]` files to fetch alongside the artifact.
    pub bundled: Vec<XBundledArtifact>,
    /// Manifest `capabilities`.
    pub capabilities: Option<Vec<String>>,
    /// Manifest `sdk` requirement.
    pub sdk: Option<String>,
}

/// One `bundledArtifacts[]` entry the fetch plan must also pull.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct XBundledArtifact {
    /// Normalized package-relative path.
    pub path: String,
    /// Optional per-file pin; verified when present.
    pub sha256: Option<String>,
}

// ─── pure planning ──────────────────────────────────────────────────────

/// Route a parsed spec to its source scheme (spec §2.3). `gh-release:` and
/// `npm:` parse today but cannot fetch yet.
///
/// # Errors
///
/// Returns a "not yet supported" message for `gh-release:` (V1.1) and
/// `npm:` (V2) specs.
pub fn route_x_spec(spec: &XSpec) -> Result<XRoute, String> {
    match &spec.source {
        XSource::Verb { verb, reference } => Ok(XRoute::Registry {
            verb: verb.clone(),
            reference: reference.clone(),
        }),
        XSource::GitHub { owner, repo, subpath, reference } => {
            let canonical_source = spec.source.canonical();
            if let Some(XGitRef::Commit(commit)) = reference {
                // Commit-pinned → immutable raw fetch, no clone needed.
                Ok(XRoute::Resolved(ResolvedFetch {
                    canonical_source,
                    commit: Some(commit.clone()),
                    plan: XFetchPlan::Raw {
                        owner: owner.clone(),
                        repo: repo.clone(),
                        commit: commit.clone(),
                        package_path: subpath.clone().unwrap_or_default(),
                        registry: None,
                    },
                }))
            } else {
                // Branch/tag/default HEAD — raw fetch cannot pin it; shallow
                // clone resolves the commit instead.
                Ok(XRoute::Resolved(ResolvedFetch {
                    canonical_source,
                    commit: None,
                    plan: XFetchPlan::Clone {
                        url: format!("https://github.com/{owner}/{repo}.git"),
                        reference: reference.as_ref().map(|named| named.as_str().to_owned()),
                        subpath: subpath.clone(),
                    },
                }))
            }
        }
        XSource::GitUrl { url, reference, subpath } => Ok(XRoute::Resolved(ResolvedFetch {
            canonical_source: spec.source.canonical(),
            commit: None,
            plan: XFetchPlan::Clone {
                url: url.clone(),
                reference: reference.as_ref().map(|named| named.as_str().to_owned()),
                subpath: subpath.clone(),
            },
        })),
        XSource::LocalDir { path } => Ok(XRoute::Resolved(ResolvedFetch {
            canonical_source: spec.source.canonical(),
            commit: None,
            plan: XFetchPlan::Local { path: path.clone() },
        })),
        XSource::GhRelease { owner, repo, tag, asset } => Err(format!(
            "x fetch: gh-release:{owner}/{repo}@{tag}#{asset} is not yet supported (V1.1) — use a bare registry verb, gh:owner/repo@<commit>, or a git URL"
        )),
        XSource::Npm { package, .. } => Err(format!(
            "x fetch: npm:{package} is not yet supported (V2) — use a bare registry verb, gh:owner/repo@<commit>, or a git URL"
        )),
    }
}

/// Resolve a registry verb entry into a fetch plan (spec §2.2 step 3d).
/// A verb with no ref (or with the entry's own commit) raw-fetches at the
/// registry pin; a foreign commit raw-fetches unpinned-by-registry; a named
/// ref falls back to the clone route (raw fetch cannot pin it).
///
/// # Errors
///
/// Returns an error when the entry's `path` is unsafe or its `commit` is not
/// a 40-lowercase-hex SHA.
pub fn resolve_x_registry_verb(
    verb: &str,
    reference: Option<&XGitRef>,
    entry: &XRegistryEntry,
    registry_owner: &str,
    registry_repo: &str,
) -> Result<ResolvedFetch, String> {
    let package_path = normalize_x_subpath(&entry.path)
        .map_err(|error| format!("x resolve: registry entry for '{verb}' has an unsafe path — {error}"))?;
    if !matches!(classify_x_git_ref(&entry.commit), XGitRef::Commit(_)) {
        return Err(format!(
            "x resolve: registry entry for '{verb}' has a non-commit pin '{}' — registry entries must pin a 40-hex commit SHA",
            entry.commit
        ));
    }
    let raw_at = |commit: &str, registry: Option<XRegistryResolution>| ResolvedFetch {
        canonical_source: XSource::GitHub {
            owner: registry_owner.to_owned(),
            repo: registry_repo.to_owned(),
            subpath: Some(package_path.clone()),
            reference: Some(XGitRef::Commit(commit.to_owned())),
        }
        .canonical(),
        commit: Some(commit.to_owned()),
        plan: XFetchPlan::Raw {
            owner: registry_owner.to_owned(),
            repo: registry_repo.to_owned(),
            commit: commit.to_owned(),
            package_path: package_path.clone(),
            registry,
        },
    };
    let registry_meta = XRegistryResolution {
        verb: verb.to_owned(),
        version: entry.version.clone(),
        capabilities: entry.capabilities.clone(),
        sha256: entry.sha256.clone(),
    };
    match reference {
        None => Ok(raw_at(&entry.commit, Some(registry_meta))),
        Some(XGitRef::Commit(commit)) if *commit == entry.commit => {
            Ok(raw_at(commit, Some(registry_meta)))
        }
        // A foreign commit is still immutable, but the registry sha256 only
        // vouches for the entry's own commit — drop it from the chain.
        Some(XGitRef::Commit(commit)) => Ok(raw_at(commit, None)),
        Some(XGitRef::Named(named)) => Ok(ResolvedFetch {
            canonical_source: XSource::GitHub {
                owner: registry_owner.to_owned(),
                repo: registry_repo.to_owned(),
                subpath: Some(package_path.clone()),
                reference: Some(XGitRef::Named(named.clone())),
            }
            .canonical(),
            commit: None,
            plan: XFetchPlan::Clone {
                url: format!("https://github.com/{registry_owner}/{registry_repo}.git"),
                reference: Some(named.clone()),
                subpath: Some(package_path),
            },
        }),
    }
}

/// URL of a registry repo's `registry.json` at `HEAD`.
#[must_use]
pub fn x_registry_url(owner: &str, repo: &str) -> String {
    format!("{X_RAW_HOST}/{owner}/{repo}/HEAD/registry.json")
}

/// Raw URL of one package file at an immutable commit:
/// `https://raw.githubusercontent.com/<owner>/<repo>/<commit>/<path>/<file>`.
/// A leading `./` on `file` is stripped; an empty `package_path` addresses
/// the repo root.
#[must_use]
pub fn x_raw_file_url(
    owner: &str,
    repo: &str,
    commit: &str,
    package_path: &str,
    file: &str,
) -> String {
    let file = file.strip_prefix("./").unwrap_or(file);
    if package_path.is_empty() {
        format!("{X_RAW_HOST}/{owner}/{repo}/{commit}/{file}")
    } else {
        format!("{X_RAW_HOST}/{owner}/{repo}/{commit}/{package_path}/{file}")
    }
}

/// Parse a `registry.json` body — a flat `verb → entry` map.
///
/// # Errors
///
/// Returns the JSON parse error, prefixed with the failing document name.
pub fn parse_x_registry(
    body: &str,
) -> Result<std::collections::BTreeMap<String, XRegistryEntry>, String> {
    serde_json::from_str(body)
        .map_err(|error| format!("x resolve: registry.json parse failed: {error}"))
}

/// Look up a verb in a parsed registry, with a nearest-name hint on miss.
///
/// # Errors
///
/// Returns an unknown-verb message naming the registry and either the
/// nearest candidate verbs or the total verb count.
pub fn lookup_x_registry_verb<'registry>(
    registry: &'registry std::collections::BTreeMap<String, XRegistryEntry>,
    verb: &str,
    registry_label: &str,
) -> Result<&'registry XRegistryEntry, String> {
    if let Some(entry) = registry.get(verb) {
        return Ok(entry);
    }
    let nearest: Vec<&str> = registry
        .keys()
        .filter(|known| known.contains(verb) || verb.contains(known.as_str()))
        .map(String::as_str)
        .collect();
    let hint = if nearest.is_empty() {
        format!("{} verbs available", registry.len())
    } else {
        format!("did you mean: {}?", nearest.join(", "))
    };
    Err(format!(
        "x resolve: unknown verb '{verb}' — not in the {registry_label} registry ({hint})"
    ))
}

/// Extract the raw-fetch facts from a fetched `plugin.json` value.
///
/// # Errors
///
/// Returns an error when required string fields are missing/mistyped or a
/// declared file path escapes the package dir.
pub fn x_manifest_fetch_info(raw: &serde_json::Value) -> Result<XManifestFetchInfo, String> {
    let string_field = |key: &str| -> Result<String, String> {
        raw.get(key)
            .and_then(serde_json::Value::as_str)
            .filter(|value| !value.is_empty())
            .map(str::to_owned)
            .ok_or_else(|| format!("x fetch: plugin.json is missing the '{key}' string field"))
    };
    let name = string_field("name")?;
    let version = string_field("version")?;
    let verb = raw
        .pointer("/cli/command")
        .and_then(serde_json::Value::as_str)
        .filter(|value| !value.is_empty())
        .map_or_else(|| name.clone(), str::to_owned);
    let target_wasm =
        raw.get("target").and_then(serde_json::Value::as_str) == Some("wasm");
    let artifact = raw.get("artifact").and_then(serde_json::Value::as_object);
    let artifact_path = artifact
        .and_then(|object| object.get("path"))
        .and_then(serde_json::Value::as_str)
        .filter(|value| !value.is_empty())
        .map(normalize_x_manifest_file)
        .transpose()?;
    let artifact_sha256 = artifact
        .and_then(|object| object.get("sha256"))
        .and_then(serde_json::Value::as_str)
        .filter(|value| !value.is_empty())
        .map(|pin| {
            normalize_plugin_install_sha256(pin).map_err(|_| {
                format!("x fetch: package '{name}' artifact.sha256 must be 64 lowercase hex chars (optionally 'sha256:'-prefixed)")
            })
        })
        .transpose()?;
    let mut bundled = Vec::new();
    if let Some(entries) = raw.get("bundledArtifacts").and_then(serde_json::Value::as_array) {
        for entry in entries {
            let object = entry
                .as_object()
                .ok_or_else(|| "x fetch: bundledArtifacts entries must be objects".to_owned())?;
            let path = object
                .get("path")
                .and_then(serde_json::Value::as_str)
                .ok_or_else(|| "x fetch: bundledArtifacts entry requires path".to_owned())?;
            let sha256 = object
                .get("sha256")
                .and_then(serde_json::Value::as_str)
                .filter(|value| !value.is_empty())
                .map(|pin| {
                    normalize_plugin_install_sha256(pin).map_err(|_| {
                        format!("x fetch: bundled artifact '{path}' sha256 must be 64 lowercase hex chars")
                    })
                })
                .transpose()?;
            bundled.push(XBundledArtifact { path: normalize_x_manifest_file(path)?, sha256 });
        }
    }
    let capabilities = raw.get("capabilities").and_then(serde_json::Value::as_array).map(|list| {
        list.iter()
            .filter_map(serde_json::Value::as_str)
            .map(str::to_owned)
            .collect::<Vec<_>>()
    });
    let sdk = raw
        .get("sdk")
        .and_then(serde_json::Value::as_str)
        .map(str::to_owned);
    Ok(XManifestFetchInfo {
        name,
        verb,
        version,
        target_wasm,
        artifact_path,
        artifact_sha256,
        bundled,
        capabilities,
        sdk,
    })
}

/// Verify the full pin chain — registry entry sha256 == manifest pin ==
/// explicit `--sha256`/`#sha256:` — returning the one normalized pin every
/// later byte-verify uses. Mismatch is fatal (`--force`-proof, spec I1).
///
/// # Errors
///
/// Returns a refusal naming the two disagreeing links, or a normalization
/// error for malformed pins.
pub fn check_x_pin_chain(
    manifest_sha256: &str,
    registry_sha256: Option<&str>,
    explicit_sha256: Option<&str>,
) -> Result<String, String> {
    let normalize = |label: &str, pin: &str| {
        normalize_plugin_install_sha256(pin).map_err(|_| {
            format!("x fetch: {label} sha256 must be 64 lowercase hex chars (optionally 'sha256:'-prefixed), got '{pin}'")
        })
    };
    let manifest = normalize("manifest", manifest_sha256)?;
    if let Some(registry) = registry_sha256 {
        let registry = normalize("registry", registry)?;
        if registry != manifest {
            return Err(format!(
                "x fetch: registry sha256 disagrees with the manifest pin — refusing.\n  registry: {registry}\n  manifest: {manifest}"
            ));
        }
    }
    if let Some(explicit) = explicit_sha256 {
        let explicit = normalize("--sha256", explicit)?;
        if explicit != manifest {
            return Err(format!(
                "x fetch: --sha256 does not match the manifest pin — refusing (mismatch is fatal, --force-proof).\n  expected: {explicit}\n  manifest: {manifest}"
            ));
        }
    }
    Ok(manifest)
}

/// The pre-`x_cache_put` byte verify: hash the fetched bytes and refuse on
/// any deviation from the chained pin, naming the URL that produced them.
///
/// # Errors
///
/// Returns the mismatch refusal (expected vs observed) or a hashing error.
pub fn verify_x_fetched_artifact(bytes: &[u8], url: &str, pin: &str) -> Result<(), String> {
    let observed = x_sha256_of_bytes(bytes)?;
    if observed == pin {
        Ok(())
    } else {
        Err(format!(
            "x fetch: sha256 mismatch for {url} — refusing to cache.\n  expected: {pin}\n  observed: {observed}"
        ))
    }
}

/// Build the `--dry-run` resolution plan from a pre-fetch [`ResolvedFetch`]
/// (spec §2.1). Fields only the fetched manifest knows (`sdk`; `sha256` for
/// non-registry plans) stay `None`; the executor returns the enriched plan.
#[must_use]
pub fn x_resolution_plan(resolved: &ResolvedFetch) -> XResolutionPlan {
    match &resolved.plan {
        XFetchPlan::Raw { commit, package_path, registry, .. } => XResolutionPlan {
            source: resolved.canonical_source.clone(),
            commit: Some(commit.clone()),
            path: (!package_path.is_empty()).then(|| package_path.clone()),
            sha256: registry.as_ref().map(|meta| meta.sha256.clone()),
            capabilities: registry.as_ref().map(|meta| meta.capabilities.clone()),
            sdk: None,
        },
        XFetchPlan::Clone { subpath, .. } => XResolutionPlan {
            source: resolved.canonical_source.clone(),
            commit: resolved.commit.clone(),
            path: subpath.clone(),
            sha256: None,
            capabilities: None,
            sdk: None,
        },
        XFetchPlan::Local { path } => XResolutionPlan {
            source: resolved.canonical_source.clone(),
            commit: None,
            path: Some(path.clone()),
            sha256: None,
            capabilities: None,
            sdk: None,
        },
    }
}

// mirrors normalize_x_subpath (x_spec.rs) but for single manifest-declared
// files: strips a leading `./`, refuses absolute/backslash/traversal paths.
fn normalize_x_manifest_file(path: &str) -> Result<String, String> {
    let trimmed = path.strip_prefix("./").unwrap_or(path);
    let valid = !trimmed.is_empty()
        && !trimmed.starts_with('/')
        && !trimmed.contains('\\')
        && trimmed
            .split('/')
            .all(|segment| !segment.is_empty() && segment != "." && segment != "..");
    if valid {
        Ok(trimmed.to_owned())
    } else {
        Err(format!(
            "x fetch: manifest file path must stay inside the package: '{path}'"
        ))
    }
}

// ─── IO edge: network + cache ───────────────────────────────────────────

/// One raw HTTP GET with a timeout. NO auth headers — public repos only
/// (mirrors the http host-fn posture). Errors always name the URL.
fn x_http_get(url: &str, timeout_secs: u64) -> Result<Vec<u8>, String> {
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|error| format!("x fetch: tokio runtime: {error}"))?;
    runtime.block_on(async {
        let client = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(timeout_secs))
            .build()
            .map_err(|error| format!("x fetch: http client: {error}"))?;
        let response = client
            .get(url)
            .send()
            .await
            .map_err(|error| format!("x fetch: GET {url} failed: {error}"))?;
        let status = response.status();
        if !status.is_success() {
            return Err(format!("x fetch: GET {url} returned HTTP {status}"));
        }
        response
            .bytes()
            .await
            .map(|bytes| bytes.to_vec())
            .map_err(|error| format!("x fetch: reading body of {url} failed: {error}"))
    })
}

/// sha256 of in-memory bytes via the shared file hasher (no extra hash dep):
/// stage → `hash_file` → clean up.
fn x_sha256_of_bytes(bytes: &[u8]) -> Result<String, String> {
    let staged = std::env::temp_dir().join(format!("maw-rs-x-hash-{}", x_cache_unique_suffix()));
    std::fs::write(&staged, bytes)
        .map_err(|error| format!("x fetch: stage bytes for hashing: {error}"))?;
    let digest = hash_file(&staged);
    let _ = std::fs::remove_file(&staged);
    digest.map_err(|error| format!("x fetch: hash staged bytes: {error}"))
}

/// Fetch and parse the registry's `registry.json` at `HEAD`. The body is
/// cached into the CAS keyed by its own sha256 (best-effort — a cache-write
/// failure never blocks resolution).
///
/// # Errors
///
/// Returns network errors (naming the URL) and registry parse errors.
pub fn fetch_x_registry(
    registry_owner: &str,
    registry_repo: &str,
    options: &XFetchOptions<'_>,
) -> Result<std::collections::BTreeMap<String, XRegistryEntry>, String> {
    let url = x_registry_url(registry_owner, registry_repo);
    let body = x_http_get(&url, options.timeout_secs)?;
    let text = String::from_utf8(body)
        .map_err(|error| format!("x resolve: {url} is not valid UTF-8: {error}"))?;
    let registry = parse_x_registry(&text)?;
    // Cache the registry body keyed by its own sha (spec §2.4 provenance);
    // never fatal — the parsed map above is the resolution input.
    if let Ok(sha) = x_sha256_of_bytes(text.as_bytes()) {
        let _ = x_cache_put(
            options.cache_root,
            &XCachePutRequest {
                artifact_name: "registry.json",
                bytes: text.as_bytes(),
                expected_sha256: &sha,
                source: &url,
                verb: format!("registry:{registry_owner}/{registry_repo}").as_str(),
                version: "HEAD",
                fetched_at: options.now,
            },
        );
    }
    Ok(registry)
}

/// Resolve a parsed spec all the way to a [`ResolvedFetch`]: pure routing,
/// plus the one network round-trip to `registry.json` for bare verbs.
///
/// # Errors
///
/// Returns unsupported-scheme errors, registry fetch/parse errors, and
/// unknown-verb errors.
pub fn resolve_x_spec(
    spec: &XSpec,
    registry_owner: &str,
    registry_repo: &str,
    options: &XFetchOptions<'_>,
) -> Result<ResolvedFetch, String> {
    match route_x_spec(spec)? {
        XRoute::Resolved(resolved) => Ok(resolved),
        XRoute::Registry { verb, reference } => {
            let registry = fetch_x_registry(registry_owner, registry_repo, options)?;
            let entry = lookup_x_registry_verb(
                &registry,
                &verb,
                &format!("{registry_owner}/{registry_repo}"),
            )?;
            resolve_x_registry_verb(&verb, reference.as_ref(), entry, registry_owner, registry_repo)
        }
    }
}

/// Execute a resolved fetch plan: raw-fetch or clone, verify through the pin
/// chain / shared WI-1 fork, land the artifact in the CAS, and return the
/// package-shaped dir plus the enriched resolution plan.
///
/// # Errors
///
/// Returns network errors, pin-chain refusals, byte-verify refusals, shared
/// verify-fork refusals, and filesystem errors — every message actionable.
pub fn execute_x_fetch(
    resolved: &ResolvedFetch,
    explicit_sha256: Option<&str>,
    options: &XFetchOptions<'_>,
) -> Result<XFetchedPackage, String> {
    match &resolved.plan {
        XFetchPlan::Raw { owner, repo, commit, package_path, registry } => {
            execute_x_raw_fetch(
                resolved,
                &RawFetchTarget { owner, repo, commit, package_path },
                registry.as_ref(),
                explicit_sha256,
                options,
            )
        }
        XFetchPlan::Clone { url, reference, subpath } => execute_x_clone_fetch(
            resolved,
            url,
            reference.as_deref(),
            subpath.as_deref(),
            explicit_sha256,
            options,
        ),
        XFetchPlan::Local { path } => execute_x_local(resolved, path, explicit_sha256),
    }
}

/// Raw-fetch coordinates, grouped to keep the executor signature small.
struct RawFetchTarget<'a> {
    owner: &'a str,
    repo: &'a str,
    commit: &'a str,
    package_path: &'a str,
}

/// The primary clone-free path (spec §2.2): GET `plugin.json`, chain-check
/// pins, GET the artifact(s), verify BEFORE `x_cache_put` (which re-verifies),
/// then assemble the package-shaped CAS entry dir.
fn execute_x_raw_fetch(
    resolved: &ResolvedFetch,
    target: &RawFetchTarget<'_>,
    registry: Option<&XRegistryResolution>,
    explicit_sha256: Option<&str>,
    options: &XFetchOptions<'_>,
) -> Result<XFetchedPackage, String> {
    let RawFetchTarget { owner, repo, commit, package_path } = *target;
    let manifest_url = x_raw_file_url(owner, repo, commit, package_path, "plugin.json");
    let manifest_bytes = x_http_get(&manifest_url, options.timeout_secs)?;
    let raw: serde_json::Value = serde_json::from_slice(&manifest_bytes)
        .map_err(|error| format!("x fetch: {manifest_url} is not valid JSON: {error}"))?;
    let info = x_manifest_fetch_info(&raw)?;
    if !info.target_wasm {
        return Err(format!(
            "x fetch: raw fetch supports ship-tier wasm packages only, but {manifest_url} does not declare target \"wasm\" — install from a git URL instead"
        ));
    }
    let (Some(artifact_path), Some(manifest_pin)) = (&info.artifact_path, &info.artifact_sha256)
    else {
        return Err(format!(
            "x fetch: package '{}' targets wasm but {manifest_url} has no artifact.path/artifact.sha256 pin — run `maw plugin build` and commit the pin",
            info.name
        ));
    };
    let pin = check_x_pin_chain(
        manifest_pin,
        registry.map(|meta| meta.sha256.as_str()),
        explicit_sha256,
    )?;

    let artifact_url = x_raw_file_url(owner, repo, commit, package_path, artifact_path);
    let artifact_bytes = x_http_get(&artifact_url, options.timeout_secs)?;
    // Verify BEFORE the bytes touch the CAS; x_cache_put re-verifies.
    verify_x_fetched_artifact(&artifact_bytes, &artifact_url, &pin)?;

    let mut bundled_files = Vec::new();
    for bundle in &info.bundled {
        let bundle_url = x_raw_file_url(owner, repo, commit, package_path, &bundle.path);
        let bytes = x_http_get(&bundle_url, options.timeout_secs)?;
        if let Some(bundle_pin) = &bundle.sha256 {
            verify_x_fetched_artifact(&bytes, &bundle_url, bundle_pin)?;
        }
        bundled_files.push((bundle.path.clone(), bytes));
    }

    let entry = x_cache_put(
        options.cache_root,
        &XCachePutRequest {
            artifact_name: x_file_name_of(artifact_path),
            bytes: &artifact_bytes,
            expected_sha256: &pin,
            source: &resolved.canonical_source,
            verb: &info.verb,
            version: &info.version,
            fetched_at: options.now,
        },
    )?;
    x_place_package_file(&entry.dir, "plugin.json", &manifest_bytes)?;
    if artifact_path != x_file_name_of(artifact_path) {
        // Nested artifact path: also lay the verified bytes out package-shaped.
        x_place_package_file(&entry.dir, artifact_path, &artifact_bytes)?;
    }
    for (path, bytes) in &bundled_files {
        x_place_package_file(&entry.dir, path, bytes)?;
    }

    Ok(XFetchedPackage {
        resolution: XResolutionPlan {
            source: resolved.canonical_source.clone(),
            commit: Some(commit.to_owned()),
            path: (!package_path.is_empty()).then(|| package_path.to_owned()),
            sha256: Some(pin),
            capabilities: info
                .capabilities
                .or_else(|| registry.map(|meta| meta.capabilities.clone())),
            sdk: info.sdk,
        },
        package_dir: entry.dir,
        cached: true,
    })
}

/// The clone fallback (spec §2.2): shallow clone at the ref into a temp dir
/// (same hygiene as `install_from_git`), resolve the commit, run the shared
/// WI-1 `verify_package_dir` fork, then land the verified artifact in the CAS.
fn execute_x_clone_fetch(
    resolved: &ResolvedFetch,
    url: &str,
    reference: Option<&str>,
    subpath: Option<&str>,
    explicit_sha256: Option<&str>,
    options: &XFetchOptions<'_>,
) -> Result<XFetchedPackage, String> {
    let tmp = create_plugin_install_temp_dir()?;
    let result =
        execute_x_clone_fetch_in_temp(resolved, url, reference, subpath, explicit_sha256, options, &tmp);
    let cleanup = std::fs::remove_dir_all(&tmp);
    match (result, cleanup) {
        (Ok(fetched), Ok(())) => Ok(fetched),
        (Err(message), _) => Err(message),
        (Ok(_), Err(error)) => Err(format!("x fetch: temp cleanup failed: {error}")),
    }
}

fn execute_x_clone_fetch_in_temp(
    resolved: &ResolvedFetch,
    url: &str,
    reference: Option<&str>,
    subpath: Option<&str>,
    explicit_sha256: Option<&str>,
    options: &XFetchOptions<'_>,
    tmp: &std::path::Path,
) -> Result<XFetchedPackage, String> {
    git_clone_plugin_repo(url, reference, tmp)?;
    let commit = x_git_head_commit(tmp)?;
    let package_dir = subpath.map_or_else(|| tmp.to_owned(), |path| tmp.join(path));
    if !package_dir.is_dir() {
        return Err(format!("x fetch: subpath not found in {url}: {}", package_dir.display()));
    }
    // The ONE shared verify fork (WI-1): manifest pin, traversal guard,
    // digest match, --sha256 mismatch fatal.
    if !x_cache_verify_package_dir(&package_dir, explicit_sha256)? {
        return Err(format!(
            "x fetch: {url} is not a ship-tier wasm package — maw x runs verified wasm packages only (V1); use `maw plugin install` for other tiers"
        ));
    }
    let manifest_bytes = std::fs::read(package_dir.join("plugin.json"))
        .map_err(|error| format!("x fetch: read cloned plugin.json: {error}"))?;
    let raw: serde_json::Value = serde_json::from_slice(&manifest_bytes)
        .map_err(|error| format!("x fetch: cloned plugin.json is not valid JSON: {error}"))?;
    let info = x_manifest_fetch_info(&raw)?;
    let (Some(artifact_path), Some(manifest_pin)) = (&info.artifact_path, &info.artifact_sha256)
    else {
        // verify_package_dir already gates this for wasm targets.
        return Err(format!(
            "x fetch: cloned package '{}' has no artifact.path/artifact.sha256 pin",
            info.name
        ));
    };
    let pin = check_x_pin_chain(manifest_pin, None, explicit_sha256)?;
    let artifact_bytes = std::fs::read(package_dir.join(artifact_path))
        .map_err(|error| format!("x fetch: read cloned artifact {artifact_path}: {error}"))?;
    let entry = x_cache_put(
        options.cache_root,
        &XCachePutRequest {
            artifact_name: x_file_name_of(artifact_path),
            bytes: &artifact_bytes,
            expected_sha256: &pin,
            source: &resolved.canonical_source,
            verb: &info.verb,
            version: &info.version,
            fetched_at: options.now,
        },
    )?;
    x_place_package_file(&entry.dir, "plugin.json", &manifest_bytes)?;
    if artifact_path != x_file_name_of(artifact_path) {
        x_place_package_file(&entry.dir, artifact_path, &artifact_bytes)?;
    }
    for bundle in &info.bundled {
        let bytes = std::fs::read(package_dir.join(&bundle.path))
            .map_err(|error| format!("x fetch: read bundled {}: {error}", bundle.path))?;
        x_place_package_file(&entry.dir, &bundle.path, &bytes)?;
    }
    Ok(XFetchedPackage {
        resolution: XResolutionPlan {
            source: resolved.canonical_source.clone(),
            commit: Some(commit),
            path: subpath.map(str::to_owned),
            sha256: Some(pin),
            capabilities: info.capabilities,
            sdk: info.sdk,
        },
        package_dir: entry.dir,
        cached: true,
    })
}

/// The local dev route (spec §2.3 `file:`): verify in place through the
/// shared fork, never write to the cache.
fn execute_x_local(
    resolved: &ResolvedFetch,
    path: &str,
    explicit_sha256: Option<&str>,
) -> Result<XFetchedPackage, String> {
    let dir = std::path::PathBuf::from(path);
    if !dir.is_dir() {
        return Err(format!("x fetch: local path is not a directory: {path}"));
    }
    let wasm = x_cache_verify_package_dir(&dir, explicit_sha256)?;
    let (sha256, capabilities, sdk, package_path) = if wasm {
        let raw = read_raw_plugin_install_manifest(&dir)?
            .ok_or_else(|| format!("x fetch: no plugin.json in {path}"))?;
        let info = x_manifest_fetch_info(&raw)?;
        (info.artifact_sha256, info.capabilities, info.sdk, path.to_owned())
    } else {
        (None, None, None, path.to_owned())
    };
    Ok(XFetchedPackage {
        resolution: XResolutionPlan {
            source: resolved.canonical_source.clone(),
            commit: None,
            path: Some(package_path),
            sha256,
            capabilities,
            sdk,
        },
        package_dir: dir,
        cached: false,
    })
}

/// Last path segment of a normalized manifest file path.
fn x_file_name_of(path: &str) -> &str {
    path.rsplit('/').next().unwrap_or(path)
}

/// Write one package file into the CAS entry dir, creating nested parents.
/// The already-verified artifact placed by `x_cache_put` is never touched
/// (callers skip when `path` equals the bare artifact name).
fn x_place_package_file(
    entry_dir: &std::path::Path,
    path: &str,
    bytes: &[u8],
) -> Result<(), String> {
    let destination = entry_dir.join(path);
    if let Some(parent) = destination.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|error| format!("x fetch: create {}: {error}", parent.display()))?;
    }
    std::fs::write(&destination, bytes)
        .map_err(|error| format!("x fetch: write {}: {error}", destination.display()))
}

/// `git -C <dir> rev-parse HEAD` — resolve the commit a clone landed on.
fn x_git_head_commit(dir: &std::path::Path) -> Result<String, String> {
    let output = std::process::Command::new("git")
        .arg("-C")
        .arg(dir)
        .arg("rev-parse")
        .arg("HEAD")
        .stdin(std::process::Stdio::null())
        .output()
        .map_err(|error| format!("x fetch: failed to run git rev-parse: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "x fetch: git rev-parse HEAD failed{}",
            command_failure_detail(&output)
        ));
    }
    let commit = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    if commit.is_empty() {
        return Err("x fetch: git rev-parse HEAD returned nothing".to_owned());
    }
    Ok(commit)
}

#[cfg(test)]
mod x_source_tests {
    use super::{
        check_x_pin_chain, execute_x_fetch, lookup_x_registry_verb, parse_x_registry, parse_x_spec,
        resolve_x_registry_verb, resolve_x_spec, route_x_spec, verify_x_fetched_artifact,
        x_raw_file_url, x_registry_url, x_resolution_plan, x_sha256_of_bytes, ResolvedFetch,
        XFetchOptions, XFetchPlan, XGitRef, XRegistryEntry, XRoute,
        X_DEFAULT_REGISTRY_OWNER, X_DEFAULT_REGISTRY_REPO,
    };

    const COSTS_COMMIT: &str = "4c34f2a99e0cc4c1dd8ccabf1a0dff25a3fde69f";
    const COSTS_SHA: &str =
        "sha256:d6fecca891f8cbb4208dcc2469be763e41013957044041adfc15423f753f553f";
    const HEX40: &str = "0123456789abcdef0123456789abcdef01234567";

    static TEMP_COUNTER: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

    fn temp_root(label: &str) -> std::path::PathBuf {
        let counter = TEMP_COUNTER.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        let dir = std::env::temp_dir().join(format!(
            "maw-rs-x-source-{label}-{}-{counter}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp root");
        dir
    }

    fn costs_entry() -> XRegistryEntry {
        XRegistryEntry {
            commit: COSTS_COMMIT.to_owned(),
            sha256: COSTS_SHA.to_owned(),
            path: "packages/20-costs".to_owned(),
            version: "1.0.0".to_owned(),
            capabilities: vec!["fs:read:claude-projects".to_owned()],
        }
    }

    fn resolved(spec: &str) -> ResolvedFetch {
        match route_x_spec(&parse_x_spec(spec).expect("parse")).expect("route") {
            XRoute::Resolved(resolved) => resolved,
            XRoute::Registry { .. } => panic!("spec '{spec}' should resolve without the registry"),
        }
    }

    // ── plan construction per scheme (pure, no network) ────────────────

    #[test]
    fn routes_bare_verb_to_registry() {
        let route = route_x_spec(&parse_x_spec("costs").expect("parse")).expect("route");
        assert_eq!(
            route,
            XRoute::Registry { verb: "costs".to_owned(), reference: None }
        );
        let route = route_x_spec(&parse_x_spec("costs@main").expect("parse")).expect("route");
        assert_eq!(
            route,
            XRoute::Registry {
                verb: "costs".to_owned(),
                reference: Some(XGitRef::Named("main".to_owned())),
            }
        );
    }

    #[test]
    fn routes_commit_pinned_github_to_raw() {
        let fetch = resolved(&format!("gh:acme/tools@{HEX40}/packages/costs"));
        assert_eq!(fetch.commit.as_deref(), Some(HEX40));
        assert_eq!(
            fetch.plan,
            XFetchPlan::Raw {
                owner: "acme".to_owned(),
                repo: "tools".to_owned(),
                commit: HEX40.to_owned(),
                package_path: "packages/costs".to_owned(),
                registry: None,
            }
        );
        assert_eq!(fetch.canonical_source, format!("gh:acme/tools@{HEX40}/packages/costs"));
    }

    #[test]
    fn routes_named_ref_and_default_head_github_to_clone() {
        let fetch = resolved("gh:acme/tools@main/packages/costs");
        assert_eq!(fetch.commit, None);
        assert_eq!(
            fetch.plan,
            XFetchPlan::Clone {
                url: "https://github.com/acme/tools.git".to_owned(),
                reference: Some("main".to_owned()),
                subpath: Some("packages/costs".to_owned()),
            }
        );
        // Shorthand without a ref → default HEAD → clone (raw cannot pin it).
        let fetch = resolved("acme/tools");
        assert_eq!(
            fetch.plan,
            XFetchPlan::Clone {
                url: "https://github.com/acme/tools.git".to_owned(),
                reference: None,
                subpath: None,
            }
        );
    }

    #[test]
    fn routes_git_url_to_clone_and_local_to_local() {
        let fetch = resolved("https://example.com/acme/tools.git@dev#packages/costs");
        assert_eq!(
            fetch.plan,
            XFetchPlan::Clone {
                url: "https://example.com/acme/tools.git".to_owned(),
                reference: Some("dev".to_owned()),
                subpath: Some("packages/costs".to_owned()),
            }
        );
        let fetch = resolved("file:./plugins/costs");
        assert_eq!(fetch.plan, XFetchPlan::Local { path: "./plugins/costs".to_owned() });
        assert_eq!(fetch.canonical_source, "file:./plugins/costs");
    }

    #[test]
    fn unsupported_schemes_name_their_milestone() {
        let error = route_x_spec(&parse_x_spec("gh-release:acme/tools@v1#x.tar.gz").expect("parse"))
            .expect_err("gh-release unsupported");
        assert!(error.contains("not yet supported (V1.1)"), "{error}");
        let error = route_x_spec(&parse_x_spec("npm:@maw-rs/costs").expect("parse"))
            .expect_err("npm unsupported");
        assert!(error.contains("not yet supported (V2)"), "{error}");
    }

    // ── registry-entry → raw-URL mapping (exact strings) ───────────────

    #[test]
    fn registry_url_is_exact() {
        assert_eq!(
            x_registry_url(X_DEFAULT_REGISTRY_OWNER, X_DEFAULT_REGISTRY_REPO),
            "https://raw.githubusercontent.com/Soul-Brews-Studio/maw-plugins/HEAD/registry.json"
        );
    }

    #[test]
    fn registry_entry_maps_to_exact_raw_file_urls() {
        let entry = costs_entry();
        let fetch = resolve_x_registry_verb(
            "costs",
            None,
            &entry,
            X_DEFAULT_REGISTRY_OWNER,
            X_DEFAULT_REGISTRY_REPO,
        )
        .expect("resolve");
        let XFetchPlan::Raw { owner, repo, commit, package_path, registry } = &fetch.plan else {
            panic!("registry verb should raw-fetch");
        };
        assert_eq!(
            x_raw_file_url(owner, repo, commit, package_path, "plugin.json"),
            "https://raw.githubusercontent.com/Soul-Brews-Studio/maw-plugins/4c34f2a99e0cc4c1dd8ccabf1a0dff25a3fde69f/packages/20-costs/plugin.json"
        );
        // Manifest artifact paths carry a "./" prefix — the URL strips it.
        assert_eq!(
            x_raw_file_url(owner, repo, commit, package_path, "./plugin.wasm"),
            "https://raw.githubusercontent.com/Soul-Brews-Studio/maw-plugins/4c34f2a99e0cc4c1dd8ccabf1a0dff25a3fde69f/packages/20-costs/plugin.wasm"
        );
        assert_eq!(
            registry.as_ref().map(|meta| meta.sha256.as_str()),
            Some(COSTS_SHA)
        );
        assert_eq!(
            fetch.canonical_source,
            format!("gh:Soul-Brews-Studio/maw-plugins@{COSTS_COMMIT}/packages/20-costs")
        );
        // Empty package path addresses the repo root without a double slash.
        assert_eq!(
            x_raw_file_url("o", "r", "c", "", "plugin.json"),
            "https://raw.githubusercontent.com/o/r/c/plugin.json"
        );
    }

    #[test]
    fn registry_verb_ref_variants() {
        let entry = costs_entry();
        // The entry's own commit keeps the registry pin in the chain.
        let fetch = resolve_x_registry_verb(
            "costs",
            Some(&XGitRef::Commit(COSTS_COMMIT.to_owned())),
            &entry,
            X_DEFAULT_REGISTRY_OWNER,
            X_DEFAULT_REGISTRY_REPO,
        )
        .expect("resolve");
        assert!(
            matches!(&fetch.plan, XFetchPlan::Raw { registry: Some(_), .. }),
            "own commit keeps registry meta"
        );
        // A foreign commit is raw-fetchable but the registry sha no longer vouches.
        let fetch = resolve_x_registry_verb(
            "costs",
            Some(&XGitRef::Commit(HEX40.to_owned())),
            &entry,
            X_DEFAULT_REGISTRY_OWNER,
            X_DEFAULT_REGISTRY_REPO,
        )
        .expect("resolve");
        assert!(
            matches!(&fetch.plan, XFetchPlan::Raw { registry: None, commit, .. } if commit == HEX40),
            "foreign commit drops registry meta"
        );
        // A named ref cannot be raw-pinned → clone fallback at that ref.
        let fetch = resolve_x_registry_verb(
            "costs",
            Some(&XGitRef::Named("main".to_owned())),
            &entry,
            X_DEFAULT_REGISTRY_OWNER,
            X_DEFAULT_REGISTRY_REPO,
        )
        .expect("resolve");
        assert_eq!(
            fetch.plan,
            XFetchPlan::Clone {
                url: "https://github.com/Soul-Brews-Studio/maw-plugins.git".to_owned(),
                reference: Some("main".to_owned()),
                subpath: Some("packages/20-costs".to_owned()),
            }
        );
    }

    #[test]
    fn registry_rejects_unsafe_entries() {
        let mut entry = costs_entry();
        entry.path = "../escape".to_owned();
        let error = resolve_x_registry_verb("costs", None, &entry, "o", "r").expect_err("traversal");
        assert!(error.contains("unsafe path"), "{error}");
        let mut entry = costs_entry();
        entry.commit = "main".to_owned();
        let error = resolve_x_registry_verb("costs", None, &entry, "o", "r").expect_err("non-commit");
        assert!(error.contains("40-hex commit"), "{error}");
    }

    #[test]
    fn parses_registry_and_looks_up_verbs() {
        let body = format!(
            r#"{{"costs":{{"commit":"{COSTS_COMMIT}","sha256":"{COSTS_SHA}","path":"packages/20-costs","version":"1.0.0","capabilities":["fs:read:claude-projects"]}},"atlas":{{"commit":"{HEX40}","sha256":"{COSTS_SHA}","path":"packages/atlas","version":"1.0.0"}}}}"#
        );
        let registry = parse_x_registry(&body).expect("parse");
        assert_eq!(registry.len(), 2);
        assert_eq!(registry["costs"], costs_entry());
        assert!(registry["atlas"].capabilities.is_empty(), "capabilities default to empty");

        let entry = lookup_x_registry_verb(&registry, "costs", "Soul-Brews-Studio/maw-plugins")
            .expect("hit");
        assert_eq!(entry.path, "packages/20-costs");

        let error = lookup_x_registry_verb(&registry, "cost", "Soul-Brews-Studio/maw-plugins")
            .expect_err("miss");
        assert!(error.contains("unknown verb 'cost'"), "{error}");
        assert!(error.contains("Soul-Brews-Studio/maw-plugins"), "{error}");
        assert!(error.contains("did you mean: costs?"), "{error}");

        let error = parse_x_registry("not json").expect_err("parse error");
        assert!(error.contains("registry.json parse failed"), "{error}");
    }

    // ── manifest fetch info ─────────────────────────────────────────────

    #[test]
    fn manifest_fetch_info_extracts_files_and_facts() {
        // The live 20-costs manifest shape (artifact.path carries "./").
        let raw: serde_json::Value = serde_json::from_str(&format!(
            r#"{{"name":"costs","version":"1.0.0","target":"wasm","sdk":"^1.0.0",
                "capabilities":["fs:read:claude-projects"],
                "cli":{{"command":"costs"}},
                "artifact":{{"path":"./plugin.wasm","sha256":"{COSTS_SHA}"}},
                "bundledArtifacts":[{{"path":"./data/model.bin","sha256":"{COSTS_SHA}"}}]}}"#
        ))
        .expect("json");
        let info = super::x_manifest_fetch_info(&raw).expect("info");
        assert_eq!(info.verb, "costs");
        assert_eq!(info.version, "1.0.0");
        assert!(info.target_wasm);
        assert_eq!(info.artifact_path.as_deref(), Some("plugin.wasm"), "./ stripped");
        assert_eq!(info.artifact_sha256.as_deref(), Some(COSTS_SHA));
        assert_eq!(info.bundled.len(), 1);
        assert_eq!(info.bundled[0].path, "data/model.bin");
        assert_eq!(info.sdk.as_deref(), Some("^1.0.0"));
        assert_eq!(
            info.capabilities.as_deref(),
            Some(&["fs:read:claude-projects".to_owned()][..])
        );

        // Traversal in a manifest file path refuses.
        let raw: serde_json::Value = serde_json::from_str(
            r#"{"name":"evil","version":"1.0.0","target":"wasm",
                "artifact":{"path":"../escape.wasm","sha256":""}}"#,
        )
        .expect("json");
        let error = super::x_manifest_fetch_info(&raw).expect_err("traversal");
        assert!(error.contains("stay inside the package"), "{error}");
    }

    // ── pin chain + byte verify refusals ───────────────────────────────

    #[test]
    fn pin_chain_accepts_agreement_and_refuses_mismatch() {
        let pin = check_x_pin_chain(COSTS_SHA, Some(COSTS_SHA), Some(COSTS_SHA)).expect("chain ok");
        assert_eq!(pin, COSTS_SHA);
        // Bare hex normalizes to the prefixed form.
        let bare = COSTS_SHA.strip_prefix("sha256:").expect("prefixed");
        assert_eq!(check_x_pin_chain(bare, None, None).expect("normalize"), COSTS_SHA);

        let other = format!("sha256:{HEX40}{}", &HEX40[..24]);
        let error = check_x_pin_chain(COSTS_SHA, Some(&other), None).expect_err("registry mismatch");
        assert!(error.contains("registry sha256 disagrees"), "{error}");
        assert!(error.contains(COSTS_SHA) && error.contains(&other), "names both pins: {error}");

        let error = check_x_pin_chain(COSTS_SHA, None, Some(&other)).expect_err("explicit mismatch");
        assert!(error.contains("--sha256 does not match"), "{error}");
        assert!(error.contains("--force-proof"), "{error}");

        let error = check_x_pin_chain("nope", None, None).expect_err("malformed");
        assert!(error.contains("64 lowercase hex"), "{error}");
    }

    #[test]
    fn verify_step_refuses_wrong_bytes() {
        let bytes: &[u8] = b"\0asm\x01\x00\x00\x00x-source-verify";
        let pin = x_sha256_of_bytes(bytes).expect("hash");
        let url = "https://raw.githubusercontent.com/o/r/c/pkg/plugin.wasm";
        verify_x_fetched_artifact(bytes, url, &pin).expect("matching bytes pass");

        let error = verify_x_fetched_artifact(b"tampered bytes", url, &pin)
            .expect_err("wrong bytes refused");
        assert!(error.contains("sha256 mismatch"), "{error}");
        assert!(error.contains(url), "names the URL: {error}");
        assert!(error.contains(&pin), "names the expected pin: {error}");
        assert!(error.contains("refusing to cache"), "{error}");
    }

    // ── --dry-run resolution plan ───────────────────────────────────────

    #[test]
    fn dry_run_plan_serializes_spec_shape() {
        let fetch = resolve_x_registry_verb(
            "costs",
            None,
            &costs_entry(),
            X_DEFAULT_REGISTRY_OWNER,
            X_DEFAULT_REGISTRY_REPO,
        )
        .expect("resolve");
        let plan = x_resolution_plan(&fetch);
        let json = serde_json::to_value(&plan).expect("serialize");
        assert_eq!(
            json,
            serde_json::json!({
                "source": format!("gh:Soul-Brews-Studio/maw-plugins@{COSTS_COMMIT}/packages/20-costs"),
                "commit": COSTS_COMMIT,
                "path": "packages/20-costs",
                "sha256": COSTS_SHA,
                "capabilities": ["fs:read:claude-projects"],
                "sdk": null,
            })
        );
        // Clone plans expose what is known pre-fetch; the rest stays null.
        let plan = x_resolution_plan(&resolved("acme/tools@main/packages/costs"));
        let json = serde_json::to_value(&plan).expect("serialize");
        assert_eq!(
            json,
            serde_json::json!({
                "source": "gh:acme/tools@main/packages/costs",
                "commit": null,
                "path": "packages/costs",
                "sha256": null,
                "capabilities": null,
                "sdk": null,
            })
        );
    }

    // ── executor: local route (offline) ────────────────────────────────

    #[test]
    fn local_route_verifies_in_place_and_never_caches() {
        let _guard = super::env_test_lock();
        let root = temp_root("local-route");
        let old = std::env::var_os("MAW_PLUGINS_LOCK");
        std::env::set_var("MAW_PLUGINS_LOCK", root.join("plugins.lock"));

        let package = root.join("pkg");
        std::fs::create_dir_all(&package).expect("package dir");
        std::fs::write(package.join("plugin.wasm"), b"\0asm\x01\x00\x00\x00x-source-local")
            .expect("wasm");
        let sha256 = maw_plugin_manifest::hash_file(&package.join("plugin.wasm")).expect("hash");
        std::fs::write(
            package.join("plugin.json"),
            format!(
                r#"{{"name":"x-source-local-demo","version":"1.0.0","target":"wasm","sdk":"^1.0.0","entry":{{"kind":"wasm","path":"plugin.wasm","export":"handle"}},"wasm":"./plugin.wasm","artifact":{{"path":"plugin.wasm","sha256":"{sha256}"}},"cli":{{"command":"x-source-local-demo"}}}}"#
            ),
        )
        .expect("manifest");

        let cache_root = root.join("cache");
        let options = XFetchOptions { cache_root: &cache_root, timeout_secs: 1, now: 1_000 };
        let spec = parse_x_spec(&format!("file:{}", package.display())).expect("parse");
        let fetch = match route_x_spec(&spec).expect("route") {
            XRoute::Resolved(resolved) => resolved,
            XRoute::Registry { .. } => panic!("file: must not hit the registry"),
        };
        let fetched = execute_x_fetch(&fetch, None, &options).expect("local execute");
        assert!(!fetched.cached, "local dev route never writes the cache");
        assert_eq!(fetched.package_dir, package);
        assert_eq!(fetched.resolution.sha256.as_deref(), Some(sha256.as_str()));
        assert_eq!(fetched.resolution.sdk.as_deref(), Some("^1.0.0"));
        assert!(!cache_root.exists(), "no cache write for local dirs");

        // A tampered local artifact refuses through the shared WI-1 fork.
        std::fs::write(package.join("plugin.wasm"), b"\0asm\x01\x00\x00\x00TAMPERED")
            .expect("tamper");
        let error = execute_x_fetch(&fetch, None, &options).expect_err("refused");
        assert!(error.contains("sha256 mismatch"), "{error}");

        match old {
            Some(value) => std::env::set_var("MAW_PLUGINS_LOCK", value),
            None => std::env::remove_var("MAW_PLUGINS_LOCK"),
        }
        let _ = std::fs::remove_dir_all(root);
    }

    // ── executor: clone fallback via a local git repo (offline) ────────

    #[test]
    fn clone_fallback_resolves_commit_verifies_and_caches() {
        let _guard = super::env_test_lock();
        let root = temp_root("clone-route");
        let old = std::env::var_os("MAW_PLUGINS_LOCK");
        std::env::set_var("MAW_PLUGINS_LOCK", root.join("plugins.lock"));

        // Build a real git repo holding one pinned wasm package.
        let repo = root.join("repo");
        let package = repo.join("packages").join("demo");
        std::fs::create_dir_all(&package).expect("package dir");
        let wasm: &[u8] = b"\0asm\x01\x00\x00\x00x-source-clone";
        std::fs::write(package.join("plugin.wasm"), wasm).expect("wasm");
        let sha256 = maw_plugin_manifest::hash_file(&package.join("plugin.wasm")).expect("hash");
        std::fs::write(
            package.join("plugin.json"),
            format!(
                r#"{{"name":"x-source-clone-demo","version":"1.2.0","target":"wasm","sdk":"^1.0.0","capabilities":["fs:read:cwd"],"entry":{{"kind":"wasm","path":"plugin.wasm","export":"handle"}},"wasm":"./plugin.wasm","artifact":{{"path":"plugin.wasm","sha256":"{sha256}"}},"cli":{{"command":"x-source-clone-demo"}}}}"#
            ),
        )
        .expect("manifest");
        for arguments in [
            vec!["init", "--initial-branch=main"],
            vec!["add", "."],
            vec![
                "-c",
                "user.email=x@test",
                "-c",
                "user.name=x-test",
                "commit",
                "-m",
                "package",
            ],
        ] {
            let output = std::process::Command::new("git")
                .arg("-C")
                .arg(&repo)
                .args(&arguments)
                .output()
                .expect("git");
            assert!(
                output.status.success(),
                "git {arguments:?}: {}",
                String::from_utf8_lossy(&output.stderr)
            );
        }

        let cache_root = root.join("cache");
        let options = XFetchOptions { cache_root: &cache_root, timeout_secs: 1, now: 2_000 };
        let fetch = ResolvedFetch {
            canonical_source: format!("file://{}", repo.display()),
            commit: None,
            plan: XFetchPlan::Clone {
                url: format!("file://{}", repo.display()),
                reference: Some("main".to_owned()),
                subpath: Some("packages/demo".to_owned()),
            },
        };
        let fetched = execute_x_fetch(&fetch, None, &options).expect("clone execute");
        assert!(fetched.cached);
        let commit = fetched.resolution.commit.as_deref().expect("resolved commit");
        assert_eq!(commit.len(), 40, "clone resolves a full commit SHA: {commit}");
        assert_eq!(fetched.resolution.sha256.as_deref(), Some(sha256.as_str()));
        assert_eq!(fetched.resolution.path.as_deref(), Some("packages/demo"));
        assert_eq!(
            fetched.resolution.capabilities.as_deref(),
            Some(&["fs:read:cwd".to_owned()][..])
        );
        // The CAS entry dir is package-shaped and holds the verified bytes.
        assert_eq!(
            std::fs::read(fetched.package_dir.join("plugin.wasm")).expect("artifact"),
            wasm
        );
        assert!(fetched.package_dir.join("plugin.json").is_file());
        let cached = super::x_cache_get(&cache_root, &sha256, 3_000).expect("cached");
        assert_eq!(cached.meta.verb, "x-source-clone-demo");
        assert_eq!(cached.meta.version, "1.2.0");

        // An explicit wrong --sha256 refuses through the shared fork.
        let wrong = x_sha256_of_bytes(b"other bytes").expect("hash");
        let error = execute_x_fetch(&fetch, Some(&wrong), &options).expect_err("pin refusal");
        assert!(error.contains("sha256"), "{error}");

        match old {
            Some(value) => std::env::set_var("MAW_PLUGINS_LOCK", value),
            None => std::env::remove_var("MAW_PLUGINS_LOCK"),
        }
        let _ = std::fs::remove_dir_all(root);
    }

    // ── live network test (manual; CI never depends on network) ────────

    /// Manual verification of the primary raw-fetch path against the real
    /// default registry. Run with:
    /// `cargo test -p maw-cli --lib x_source -- --ignored live_fetch`
    #[test]
    #[ignore = "network: fetches the live registry + 20-costs raw files from GitHub — run manually"]
    fn live_fetch_costs_via_registry() {
        let root = temp_root("live");
        let cache_root = root.join("cache");
        let options = XFetchOptions { cache_root: &cache_root, timeout_secs: 30, now: 1_000 };
        let spec = parse_x_spec("costs").expect("parse");
        let fetch = resolve_x_spec(
            &spec,
            X_DEFAULT_REGISTRY_OWNER,
            X_DEFAULT_REGISTRY_REPO,
            &options,
        )
        .expect("registry resolution");
        assert!(matches!(&fetch.plan, XFetchPlan::Raw { .. }), "bare verb raw-fetches");
        let fetched = execute_x_fetch(&fetch, None, &options).expect("raw fetch + verify");
        assert!(fetched.cached);
        let pin = fetched.resolution.sha256.as_deref().expect("pinned");
        assert!(pin.starts_with("sha256:"), "{pin}");
        assert!(fetched.package_dir.join("plugin.json").is_file());
        // The cached artifact re-verifies on read (poison-inert CAS).
        let entry = super::x_cache_get(&cache_root, pin, 2_000).expect("verified read");
        assert_eq!(entry.meta.verb, "costs");
        let _ = std::fs::remove_dir_all(root);
    }
}
