[package]
name = "maw-peer"
version = "0.1.0-alpha.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
maw-xdg = { git = "https://github.com/Soul-Brews-Studio/maw-crates", rev = "e46932081dfd1a20bb962506086f1befe5525fa4" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]

[lints]
workspace = true
